# GET http://localhost:3000/api/students/1
# DELETE http://localhost:3000/api/students/6

# POST http://localhost:3000/api/students
# Content-Type: application/json

# {
#     "nome": "noNome",
#     "cognome": "noCognome",
#     "email": "no@gmail",
#     "data_nascita": "12-12-12"
# }

# PUT http://localhost:3000/api/students/8
# Content-Type: application/json

# {
#     "email": "modificata@gmail",
#     "data_nascita": "10-10-10"
# }